name: streamly
description: A modern minimalist YouTube clone Flutter app powered by custom Node.js backend.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.3
  flutter_secure_storage: ^5.0.2
  video_player: ^2.4.5
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  google_fonts: ^4.0.4
  shared_preferences: ^2.5.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/appicon.png
    - assets/icon.png
    - assets/playbutton.png
    - assets/streamly.png
    - assets/streamly2.png
